:sparkles: modificação do alinhamento da galeria em telas grandes
thebonfiretech/lading-page pull request #2
Opened 2024-07-19 12:41 UTC by Gabi-Viana

Testei e agora em telas grandes, a galeria está alinhada. Aguardo retorno!

2024-07-19 16:47 UTC, odutradev requested changes

2024-07-19 16:47 UTC, odutradev commented on src/components/miniGallery/styles.js
>  export const GalleryPhotos2 = styled.div`
apague esse componente

2024-07-19 16:47 UTC, odutradev commented on src/components/miniGallery/styles.js
>  export const GalleryPhotos = styled.div`
modifique esse componente com nome GalleryPhotos e insira uma props "reverse".

em flex-direction  vc verifica se é falso ou verdadeiro

e na parte onde usa o componente, o primeiro vc coloca reverse={false} e o segundo coloca true

2024-07-19 16:47 UTC, odutradev commented on src/components/miniGallery/styles.js
>  export const GalleryPhotos = styled.div`
assim reduz bastante a quantidade de codigo

2024-07-19 16:52 UTC, Gabi-Viana commented on src/components/miniGallery/styles.js
>  export const GalleryPhotos = styled.div`
Blz, vou fazer isso assim que chegar em casa

2024-07-22 20:03 UTC, odutradev approved these changes

2024-07-22 20:03 UTC, merged